name: Check external links

on:
  schedule:
    - cron: "17 3 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  link-checker:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Link Checker 🔗
        uses: lycheeverse/lychee-action@v2.1.0
        with:
          fail: true
          # removed md files that include liquid tags
          args: --user-agent 'curl/7.54' --exclude-path README.md --exclude-path _pages/404.md --verbose --no-progress './**/*.md' './**/*.html'
